services:
  wireguard-dev:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-dev
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - SERVERURL=127.0.0.1     
      - SERVERPORT=51820
      - PEERS=devpeer           
      - PEERDNS=auto
      - LOG_CONFS=true
    volumes:
      - ./wireguard/config:/config
      - /dev/net/tun:/dev/net/run
    restart: unless-stopped