apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gophergate-wg-agent
    labels:
        app: gophergate
spec:
    selector:
        matchLabels:
            app: gophergate-wg-agent
    template:
        metadata:
            labels:
                app: gophergate-wg-agent
        spec:
            containers:
                - name: gophergate-wg-agent
                  image: '{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}'
                  imagePullPolicy: '{{ .Values.agent.image.pullPolicy }}'
                  resources:
                      requests:
                          cpu: '{{ .Values.agent.resources.requests.cpu }}'
                          memory: '{{ .Values.agent.resources.requests.memory }}'
                      limits:
                          cpu: '{{ .Values.agent.resources.limits.cpu }}'
                          memory: '{{ .Values.agent.resources.limits.memory }}'
                  env:
                      - name: DATABASE_URL
                        value: postgres://gg_admin:$(DB_PASSWORD)@gophergate-postgresql:5432/gophergate?sslmode=disable
                      - name: DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: gophergate-db-credentials
                            key: password
                      - name: GRPC_ADDR
                        value: '{{ .Values.agent.env.GRPC_ADDR }}'
            nodeSelector:
                role: vpn
            tolerations:
                - key: 'dedicated'
                  operator: 'Equal'
                  value: 'vpn'
                  effect: 'NoSchedule'
