syntax = "proto3";

package gateway.v1;

option go_package = "github.com/Cyrof/GopherGate/gophergate-core/pkg/gen/gateway/v1;gatewayv1";

// Core Data Types

message PeerStatus {
    string public_key           = 1;
    string endpoint             = 2;
    repeated string allowed_ips = 3;
    string handshake            = 4;
    uint64 rx_bytes             = 5;
    uint64 tx_bytes             = 6;
    string keepalive            = 7;
}

// overall wiregaurd state
message DeviceStatus {
    string iface              = 1;
    int32 listen_port         = 2;
    int32 firewall_mark       = 3;
    string public_key         = 4;
    repeated PeerStatus peers = 5;
}

// Create

message CreatePeerRequest {
    string iface                  = 1;
    string name                   = 2;
    string public_key             = 3;
    repeated string allowed_cidrs = 4;
    string endpoint               = 5;
    int32 keepalive_seconds       = 6;
    bool replace_allowed_ips      = 7;
}

message CreatePeerResponse {
    string iface        = 1;
    string name         = 2;
    string public_key   = 3;
    bool config_applied = 4;
}

// Read

message GetPeerRequest {
    string iface      = 1;
    string public_key = 2;
}

message GetPeerResponse { PeerStatus peer = 1; }

message ListPeerRequest { string iface = 1; }

message ListPeerResponse { repeated PeerStatus peers = 1; }

// Update

message UpdatePeerRequest {
    string iface                         = 1;
    string public_key                    = 2;
    repeated string set_allowed_cidrs    = 3;
    repeated string append_allowed_cidrs = 4;
    string endpoint                      = 5;
    int32 keepalive_seconds              = 6;
}

message UpdatePeerResponse {
    string iface      = 1;
    string public_key = 2;

    message Changed {
        bool allowed_ips = 1;
        bool endpoint    = 2;
        bool keepalive   = 3;
    }

    Changed changed = 3;
}

// Delete

message DeletePeerRequest {
    string iface      = 1;
    string public_key = 2;
}

message DeletePeerResponse {
    string iface      = 1;
    string public_key = 2;
    bool removed      = 3;
}

// Wireguard Services
service WireGuardService {
    rpc CreatePeer(CreatePeerRequest) returns (CreatePeerResponse);
    rpc GetPeer(GetPeerRequest) returns (GetPeerResponse);
    rpc ListPeer(ListPeerRequest) returns (ListPeerResponse);
    rpc UpdatePeer(UpdatePeerRequest) returns (UpdatePeerResponse);
    rpc DeletePeer(DeletePeerRequest) returns (DeletePeerResponse);
}
